MyClient_Core/MyClient_Core/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace MyClient_Core.Models
{
    public class ApplicationDbContext:DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options):base(options)
        {

        }
        public DbSet<Clients> Clients
        { get; set; }
    }
}

MyClient_Core/MyClient_Core/Models/Clients.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyClient_Core.Models
{
    public class Clients
    {
        [Key]
        [Display(Name = "Cliente ID")]
        public int Clieid { get; set; }

        [Required(ErrorMessage = "Introduce nombre del cliente")]
        [Display(Name = "Nombre del Cliente")]
        public String Cliename { get; set; }

        [Required(ErrorMessage = "Introduce la edad del cliente")]
        [Display(Name = "Edad del Cliente")]
        [Range(18, 100)]
        public int Age { get; set; }

        [Required(ErrorMessage = "Introduce el e-mail del cliente")]
        [Display(Name = "E-mail del Cliente")]
        public String Mail { get; set; }

        [Required(ErrorMessage = "Introduce credito del cliente")]
        [Display(Name = "Credito del Cliente")]
        public int Credit { get; set; }

    }
}

MyClient_Core/MyClient_Core/Models/ErrorViewModel.cs
using System;

namespace MyClient_Core.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyClient_Core/MyClient_Core/Controllers/MyClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyClient_Core.Models;

namespace MyClient_Core.Controllers
{
    public class MyClientController : Controller
    {
        private readonly ApplicationDbContext d_b;
        public MyClientController (ApplicationDbContext db)
        {
            d_b = db;
        }

        // GET: HomeController1
        public ActionResult Index()
        {
            var displaydata = d_b.Clients.ToList();
            return View(displaydata);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string ClieSearch)
        {
            ViewData["GetClient"] = ClieSearch;
            var clquery = from x in d_b.Clients select x;
            if(!String.IsNullOrEmpty(ClieSearch))
            {
                clquery = clquery.Where(x => x.Cliename.Contains(ClieSearch) || x.Mail.Contains(ClieSearch));
            }
            return View(await clquery.AsNoTracking().ToListAsync());
        }

        // GET: HomeController1/Details/5
        public async Task <IActionResult> Detail(int? id)
        {
            if (id==null)
            {
                return RedirectToAction("Index");
            }
            var getClieDetail = await d_b.Clients.FindAsync(id);
            return View(getClieDetail);
        }

        // GET: HomeController1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController1/Create
        [HttpPost]
        public async Task<IActionResult> Create (Clients newC)
        {
            if(ModelState.IsValid)
            {
                d_b.Add(newC);
                await d_b.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(newC);
        }

        // GET: HomeController1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id==null)
            {
                return RedirectToAction("Index");
            }
            var getClieDetail = await d_b.Clients.FindAsync(id);
            return View(getClieDetail);
        }

        // POST: HomeController1/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(Clients oldC)
        {
            if(ModelState.IsValid)
            {
                d_b.Update(oldC);
                await d_b.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldC);
        }

        // GET: HomeController1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getClieDetail = await d_b.Clients.FindAsync(id);
            return View(getClieDetail);
        }

        // POST: HomeController1/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
           
                var getClieDetail = await d_b.Clients.FindAsync(id);
                d_b.Clients.Remove(getClieDetail);
                await d_b.SaveChangesAsync();
                return RedirectToAction("Index");
           
        }
    }
}

MyClient_Core/MyClient_Core/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyClient_Core/MyClient_Core/Views/MyClient/Create.cshtml
@model MyClient_Core.Models.Clients

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Clients</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cliename" class="control-label"></label>
                <input asp-for="Cliename" class="form-control" />
                <span asp-validation-for="Cliename" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credit" class="control-label"></label>
                <input asp-for="Credit" class="form-control" />
                <span asp-validation-for="Credit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyClient_Core/MyClient_Core/Views/MyClient/Delete.cshtml
@model MyClient_Core.Models.Clients

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>¿Realmente desea borrar la información?</h3>
<div>
    <h4>Clients</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clieid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clieid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliename)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliename)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Credit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Credit)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyClient_Core/MyClient_Core/Views/MyClient/Detail.cshtml
@model MyClient_Core.Models.Clients

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>Clients</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clieid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clieid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliename)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliename)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Credit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Credit)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Clieid }) |
    <a asp-action="Index">Back to List</a>
</div>

MyClient_Core/MyClient_Core/Views/MyClient/Edit.cshtml
@model MyClient_Core.Models.Clients

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Clients</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Clieid" class="control-label"></label>
                <input asp-for="Clieid" class="form-control" readonly />
                <span asp-validation-for="Clieid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cliename" class="control-label"></label>
                <input asp-for="Cliename" class="form-control" />
                <span asp-validation-for="Cliename" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credit" class="control-label"></label>
                <input asp-for="Credit" class="form-control" />
                <span asp-validation-for="Credit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyClient_Core/MyClient_Core/Views/MyClient/Index.cshtml
@model IEnumerable<MyClient_Core.Models.Clients>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Clientes</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-action="Index" method="get">
    <p>
        <input type="search" placeholder="Ingresa Nombre o Email" name="ClieSearch"
               value="@ViewData["GetClient"]" style="width:500px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index">Ver todos</a>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Clieid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cliename)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mail)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Clieid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cliename)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mail)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Clieid }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Detail", new { id = item.Clieid }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Clieid }, new { @class = "btn btn-primary" })
            </td>
        </tr>
}
    </tbody>
</table>

MyClient_Core/MyClient_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyClient_Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="MyClient" asp-action="Index">MyClient_Core</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyClient" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MyClient_Core - <a asp-area="" asp-controller="MyClient" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>